# Generated by Django 4.1.4 on 2023-01-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_game_slug_alter_player_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='duration',
            field=models.IntegerField(default=30),
        ),
    ]
