# Generated by Django 4.1.4 on 2023-01-10 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_game_slug_alter_player_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fig',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figs', to='main.config'),
        ),
        migrations.AlterField(
            model_name='fig',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figs', to='main.building'),
        ),
        migrations.AlterField(
            model_name='fig',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figs', to='main.player'),
        ),
    ]
